### ISSUE TITLE
About Licensing Redistibution and Trademark

### ISSUE THREAD

**Issue by Beryesa** [CleoMenezes/Custom-Adwaita-Folder-Icons#4]
These icons are looking great, Thanks!

But some logos used here may not be free to distribute.
What about changing them to something recognizable while not same?
Like what kde did with java icons 
https://commons.wikimedia.org/wiki/File:Breezeicons-mimetypes-64-application-x-java.svg
![application-x-java](https://upload.wikimedia.org/wikipedia/commons/c/cb/Breezeicons-mimetypes-64-application-x-java.svg)

And can I ask why PNGs and not SVGs?

**Comment by CleoMenezesJr** [comment]
Thank you very much, I was warned before, but sincerely I simply preferred to believe that not having a license might help, but since this is the second time I have been warned I preferred to create [this solution](https://github.com/CleoMenezes/Custom-Adwaita-Folder-Icons/blob/main/Java.png).
The truth is that I had made about 10 icons in png and ended up making them all in png. The truth is that I regret it now because it makes it difficult to receive contributions. In the future I will make it available in SVG.
